name: Archive UWP

# Allow Release
permissions: write-all

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:

  archive_uwp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Query Package
      run: |
        output=ROBLOXCORPORATION.ROBLOX_2025.1011.420.0_neutral_55nm5eh3cm0pr
        echo "RELEASE_TAG=$(echo "$output")" >> $GITHUB_ENV
        
    - name: Check if release exists
      run: |
        response=$(curl --silent "https://api.github.com/repos/Yakov5776/RobloxUWP-StoreLib/releases/tags/${{ env.RELEASE_TAG }}")
        id=$(echo "$response" | jq '.id' -r)
        echo "EXISTING_RELEASE=$id" >> $GITHUB_ENV
    
    - name: Download Package
      if: env.EXISTING_RELEASE == 'null'
      run: |
        curl -L "http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/8d974edf-4f26-46ec-86c5-43b9f9d1f8b0?P1=1760889924&P2=404&P3=2&P4=k010OTqvngLNgxY%2bsw222yZCG0Uv5d1hE8K4hKuEy52Ey%2bIFYaI4k9Uv7SSQYcGK2w%2bf08XKiaw2SFJABEqSUw%3d%3d" -o "ROBLOXCORPORATION.ROBLOX_2025.1011.420.0_neutral_._55nm5eh3cm0pr.msixbundle"

    - name: Calculate file size
      if: env.EXISTING_RELEASE == 'null'
      run: |
        size=$(du -b *.msixbundle | cut -f1)
        echo "FILE_SIZE=$(echo "$size")" >> $GITHUB_ENV
        
    - name: Pushing to release
      uses: ncipollo/release-action@v1
      if: env.EXISTING_RELEASE == 'null' && env.FILE_SIZE > 2097152 # 2mb in size
      with:
        name: ${{ env.RELEASE_TAG }}
        tag: ${{ env.RELEASE_TAG }}
        body: ${{ env.RELEASE_TAG }}
        commit: ${{ github.sha }}
        artifacts: "*.msixbundle"
        allowUpdates: true
        removeArtifacts: false
        replacesArtifacts: false
