name: Archive UWP

# Allow Release
permissions: write-all

on:
  workflow_dispatch:
jobs:

  archive_uwp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build
      
    - name: Query Package
      run: |
        OUTPUT=$(dotnet run --project RobloxUWP-StoreLib -query)
        echo "RELEASE_TAG=$(echo "$output")" >> $GITHUB_ENV
    
    - name: Download Package
      run: dotnet run --project RobloxUWP-StoreLib
        
    - name: Pushing to release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.RELEASE_TAG }}
        tag: ${{ env.RELEASE_TAG }}
        commit: ${{ github.sha }}
        artifacts: msixbundle
        allowUpdates: true
        removeArtifacts: false
        replacesArtifacts: false
