name: Archive UWP

# Allow Release
permissions: write-all

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:

  archive_uwp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build
      
    - name: Query Package
      run: |
        output=$(dotnet run --project RobloxUWP-StoreLib -query)
        echo "RELEASE_TAG=$(echo "$output")" >> $GITHUB_ENV
        
    - name: Check if release exists
      run: |
        response=$(curl --silent "https://api.github.com/repos/Yakov5776/RobloxUWP-StoreLib/releases/tags/${{ env.RELEASE_TAG }}")
        id=$(echo "$response" | jq '.id' -r)
        echo "EXISTING_RELEASE=$id" >> $GITHUB_ENV
    
    - name: Download Package
      run: dotnet run --project RobloxUWP-StoreLib
      if: env.EXISTING_RELEASE == 'null'

    - name: Calculate file size
      if: env.EXISTING_RELEASE == 'null'
      run: |
        size=$(du -b *.msixbundle | cut -f1)
        echo "FILE_SIZE=$(echo "$size")" >> $GITHUB_ENV
        
    - name: Pushing to release
      uses: ncipollo/release-action@v1
      if: env.EXISTING_RELEASE == 'null' && env.FILE_SIZE > 2097152 # 2mb in size
      with:
        name: ${{ env.RELEASE_TAG }}
        tag: ${{ env.RELEASE_TAG }}
        body: ${{ env.RELEASE_TAG }}
        commit: ${{ github.sha }}
        artifacts: "*.msixbundle"
        allowUpdates: true
        removeArtifacts: false
        replacesArtifacts: false
