name: .NET Core Desktop

on:
  push:
    paths-ignore:
      - '.github/workflows/*'
      - '*.md'
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build
